// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsqleacqgulrnahalpta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzcWxlYWNxZ3Vscm5haGFscHRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MDMxMTgsImV4cCI6MjA3MjI3OTExOH0.RfVZRpEeow3dLnAJBJSkGQdKfhPlMbPymicVyS8FwV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});